"""empty message

Revision ID: 5a84fc815290
Revises: 7fb2682e5151
Create Date: 2017-12-21 02:18:31.989847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a84fc815290'
down_revision = '7fb2682e5151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LiftHistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Notes', sa.Text(), nullable=True))

    with op.batch_alter_table('WorkoutHistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WorkoutHistory', schema=None) as batch_op:
        batch_op.drop_column('Notes')

    with op.batch_alter_table('LiftHistory', schema=None) as batch_op:
        batch_op.drop_column('Notes')

    # ### end Alembic commands ###
