"""empty message

Revision ID: 7fb2682e5151
Revises: 
Create Date: 2017-12-17 15:44:37.064576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.

revision = '7fb2682e5151'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Lifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('BodyweightMultiplier', sa.Numeric(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Lifts', schema=None) as batch_op:
        batch_op.drop_column('BodyweightMultiplier')
    # ### end Alembic commands ###
